spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: 33366666622
mybatis: # type을 쉽게 쓰기 위해서 com.may.dto 패키지를 type-aliaes에 설정
  type-aliases-package: com.may.dto